variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository" # Use a local maven cache


image: maven:latest

stages:
  - build
  - test
  - format-check
  #- sonarqube # Uncomment when SonarQube is ready to be used

cache:
  paths:
  - .m2/repository

maven_build:
  stage: build
  script:
    - echo "Starting Maven build process..."
    - mvn clean test-compile
  artifacts:
    paths:
      - target/
    
unit_tests:
  stage: test
  dependencies:
    - maven_build
  script:
    - echo "Running unit tests..."
    - mvn surefire:test -Dtest=fr.ensimag.deca.tools.SymbolTest
    - mvn surefire:test -Dtest=fr.ensimag.deca.TestCompilerOptions
    - mvn surefire:test -Dtest=fr.ensimag.deca.context.TestEnvironmentExp

non_regression_tests:
  stage: test
  dependencies:
    - maven_build
  script:
    - echo "Running non-regression tests..."
    - mvn exec:exec@non-regression

decac_verif_tests:
  stage: test
  dependencies:
    - maven_build
  script:
    - echo "Running decac verification tests..."
    - mvn exec:exec@decac-verif
  
spotless_check:
  stage: format-check
  script:
  - echo "Checking code formatting with Spotless..."
  - mvn spotless:check
  allow_failure: false


# Uncomment the section below to enable SonarQube analysis
# sonarqube-check:
#   stage: sonarqube
#   image: registry.gitlab.com/ensimag5044950/projet-gl/custom-maven-image:latest
#   cache:
#     key: "${CI_JOB_NAME}"
#     paths:
#       - .sonar/cache
#   script:
#     - echo "Running SonarQube analysis..."
#     - mvn verify sonar:sonar -Dsonar.projectKey=Project-GL -Dsonar.login=$SONAR_TOKEN
#   allow_failure: true
