stages:
  - build
  - test

maven_build:
  stage: build
  image: registry.gitlab.com/ensimag5044950/projet-gl/custom-maven-image:latest
  script:
    - mvn clean compile
  artifacts:
    paths:
      - target/
    expire_in: 1 hour

common_tests:
  stage: test
  image: registry.gitlab.com/ensimag5044950/projet-gl/custom-maven-image:latest
  dependencies:
    - maven_build
  script:
    - chmod +x src/test/script/common-tests.sh
    - mvn exec:exec@common-tests
