stages:
  - build
  - test

maven_build:
  stage: build
  image: maven:3.9.4-eclipse-temurin-11
  script:
    - mvn clean compile
  artifacts:
    paths:
      - target/
    expire_in: 1 hour

common_tests:
  stage: test
  image: maven:3.9.4-eclipse-temurin-11
  dependencies:
    - maven_build
  script:
    - chmod +x src/test/script/common-tests.sh
    - mvn exec:exec@common-tests
